#!/bin/bash
cat <<'EOF'
wifite - Auditoria de redes WiFi WPA

Dicionários de senhas:
  https://github.com/danielmiessler/SecLists/tree/master/Passwords/WiFi-WPA

Executar ataque de dicionário WPA:
  wifite --dict /home/kali/Downloads/probable-v2-wpa-top4800.txt
EOF
