#!/usr/bin/env bash

ROOT_DIR="$(dirname $(dirname $(realpath $0)))"

echo "Para melhor usabilidade da ferramenta"
echo "Adicione $ROOT_DIR/bin ao seu \$PATH:"
echo "$ echo \"PATH=\$PATH:$ROOT_DIR/bin\" >> ~/.bashrc"
echo "Habilite o autocomplete:"
echo "$ echo \"source $ROOT_DIR/lib/shconf-autocomplete.sh\" >> ~/.bashrc"
