#!/bin/bash
cat <<'EOF'
SonarQube - Configuração e uso

Pré-requisito (pode ser necessário):
  sysctl -w vm.max_map_count=524288

Executar análise com Maven:
  mvn clean verify sonar:sonar \
    -Dsonar.projectKey=Econt-Agro \
    -Dsonar.host.url=http://localhost:9000 \
    -Dsonar.login=<token> \
    -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
EOF
